name: run-tests

on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1,8.0, 7.4, 7.3]
        laravel: [^8.12, ^9.0, 10.0]
        exclude:
          - php: 8.0
            laravel: 10.0
          - php: 7.4
            laravel: 10.0
          - php: 7.3
            laravel: 10.0
          - php: 7.3
            laravel: '^9.0'
          - php: 7.4
            laravel: '^9.0'

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, fileinfo, ftp, redis, memcached
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require "illuminate/contracts=${{ matrix.laravel }}" --prefer-dist --no-interaction --no-update
            composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.clover
